### ISSUE TITLE
基于 GitHub Issues 的博客系统

### ISSUE THREAD

**Issue by iori2333** [iori2333/blog-posts#1]
# 基于 GitHub Issues 的博客系统

**Comment by iori2333** [comment]
## 起因

一直以来，我都没有写博客的习惯。虽然平时也会对开发中遇到的一些技术问题进行简单总结，但没有将这些文字发表到互联网上。原因有很多，比如懒（主要原因）、不知道写什么、不想搭建博客系统等等。然而，某一日我发现自己的记录似乎有些过于零散，有时候会忘记之前是怎么解决的问题，于是我决定搭建一个博客系统，将自己的一些技术总结和心得体会记录下来。同时因为博客是写给别人看的，故我在总结时会更加认真，也能够更好地理清思路。

既然确立了搭建博客的目标，那么接下来就是选择搭建博客的方式了。目前搭建博客的方式很多，也很简单。一种常见的方式是使用 Hexo、Hugo 这类工具链将 Markdown 文件编译成静态网页，然后部署到 GitHub Pages 上。这种方式的好处是简单、快速，同时依赖于 GitHub 的服务器，也不需要额外的金钱投入。然而，在尝试折腾了 Hexo 后，我还是放弃了这种做法，因为我发现自己对默认主题不太满意，而花费了大量时间微调样式，反而浪费了我写博客的时间。同时，我发现如果要在 Github Pages 上实现评论功能，需要引入第三方评论插件，这对我来说又是一个额外的负担。

### GitHub Issues

在搜索如何为 Github Pages 实现评论功能时，我发现了一个很有意思的项目：[Gitment](https://github.com/imsun/gitment)，该项目利用了 GitHub Issues 的评论功能，通过发 Issue 的方式间接实现了静态网页的评论功能。我意识到，既然 GitHub Issues 可以实现评论功能，那么为何不直接用 Issues 来写博客呢？这样一来，我就可以直接在 Issues 中写博客，同时免去了纠结博客主题的烦恼（毕竟 Github 不能自定义主题），也不需要担心评论功能的实现。同时，GitHub Issues 本身也具有实现博客的所有要求，例如 Markdown 语法、标签分类、置顶等。

### 实现

现在的问题是，如何将 Markdown 文件转换为博客文章，并且发表在 Issues 里？这里我使用了 GitHub Actions 来实现这一功能。具体来说，我创建了一个 GitHub Actions Workflow，当我在 `docs` 目录下创建一个新的 Markdown 文件时，该 Workflow 会自动将该文件转换为博客文章，并且在博客首页展示最新的文章。这样一来，我只需要在本地写好 Markdown 文件，然后 push 到 GitHub 上，博客就会自动出现在 Issues 列表中了。

具体地，这个 Action 共分为三个步骤：

1. 读取 `docs` 目录下的所有 Markdown 文件，并且提取文件的元信息（标题、日期、标签等）。为了方便起见，我在每一个 Markdown 文件的头部添加了元信息，例如：
```markdown
> title: 基于 GitHub Issues 的博客系统
> date: 2024-05-15
> tags: [自动化, GitHub, Issues, 博客]
```
这里的元信息使用了类似 YAML 的格式，方便解析。
2. 分段：我不希望 Issues 中的内容过长，因此我将文章按照一级、二级标题分段，每一段作为一个评论发布到 Issues 中。这样一来，每一层楼不至于过长，同时也方便阅读。
3. 发布：最后，将分段后的内容发布到 Issues 中。同时，我还会将文章的元信息中的 tag 作为 Issue 的标签，方便分类。

此外，由于写作时可能引入了相对路径的图片，这导致本地可以正常显示图片，但是在 Issues 中却无法找到。好在 Push 到 Github 后，每一张图片的 Blob 链接都可以通过其相对路径计算获取，因此在处理时只需要将对应的路径替换为 Blob 链接即可。

这个 Action 可以在[这里](https://github.com/iori2333/post-to-issue)找到。如果你也想使用这个 Action，可以写一个 Workflow：

```yaml
name: Post articles
on:
push:
branches:
- main # 需要是文章所在分支
jobs:
post:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Post
uses: iori2333/post-to-issue@master
with:
token: "${{ secrets.TOKEN }}" # 提前配置的 GitHub Token
branch: main
```

### 未来的计划

- [ ] 添加元数据，避免每一次更新都需要解析全部 Markdown 文件并在发布时检查重复。
- [ ] 为`README.md`添加文章列表，例如最近的文章、标签分类等。
- [ ] 提供更多的自定义选项，例如是否分段、发布到的 Issues 仓库等。
